apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: spreadit-deploy-course-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODULE_SERVICE_URL
              value: "http://module-service:8000"
            - name: RABBIT_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_URL
---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
  type: NodePort
